---
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present 

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Grab python dependencies
      apt: name={{item}} state=installed
      with_items:
        - python-pip
        - python-scipy
        - liblapack-dev
        - libopenblas-dev
        - gfortran
        - libpython3-dev
        - build-essential
        - pkg-config
 
    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - pandas
        - scipy
        - numpy 
        - pandasql 
        - scikit-learn
        - ggplot
        - matplotlib