---
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    #- name: Safe system upgrade via aptitude
    #  apt: upgrade=safe

    - name: grab build dependencies for numpy and scipy
      command: apt-get -y build-dep python-scipy liblapack-dev libopenblas-dev gfortran libpython3-dev build-essential pkg-config python-pip

    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - pandas
        - scipy
        - numpy 
        - pandasql 
        - scikit-learn
        - ggplot
        - matplotlib